apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: 
  labels: 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
  template: 
    metadata: 
      labels: 
    spec: 
      containers: 
      - name: 
        image: 
        ports: 
        - containerPort: 80