apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service
spec:
  selector:
    matchLabels:
      app: simple-web-service
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-web-service
    spec:
      containers:
        - name: simple-web-service
          image: pengbai/docker-supermario
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  selector:
    app: simple-web-service
  ports:
  - protocol: "TCP"
    port: 8600
    targetPort: 8080
  type: LoadBalancer