apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment
  labels: 
    app: nginx
    lkj: kljl
    ljlkj: ljkljlk
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
      lkj: kljl
      ljlkj: ljkljlk
  template: 
    metadata: 
      labels: 
        app: nginx
        lkj: kljl
        ljlkj: ljkljlk
    spec: 
      containers: 
      - name: nginx
        image: nginx:1.15.4
        ports: 
        - containerPort: 80