- job_name: 35.185.210.221
  metrics_path: /api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/federate
  scheme: https
  params:
    match[]:
    - '{job=~"node.*"}'
    - '{job=~"container.*"}'
    - '{job=~"kube.*"}'
  static_configs:
  - targets:
    - 35.185.210.221
  basic_auth:
    username: admin
    password: gQUd1wSvMAssWQtD
  tls_config:
    insecure_skip_verify: true
- job_name: 35.238.223.32
  metrics_path: /api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/federate
  scheme: https
  params:
    match[]:
      - '{job=~"node.*"}'
      - '{job=~"container.*"}'
      - '{job=~"kube.*"}'
  static_configs:
    - targets:
        - 35.238.223.32
  basic_auth:
    username: admin
    password: X1O81b496f2mQK4F
  tls_config:
    insecure_skip_verify: true
- job_name: 35.222.94.136
  metrics_path: /api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/federate
  scheme: https
  params:
    match[]:
      - '{job=~"node.*"}'
      - '{job=~"container.*"}'
      - '{job=~"kube.*"}'
  static_configs:
    - targets:
        - 35.222.94.136
  basic_auth:
    username: admin
    password: 5p7H8fQ0u3WGIITW
  tls_config:
    insecure_skip_verify: true