apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
  
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'
  
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
    
        static_configs:
          - targets: ['localhost:9090']
          
      - job_name: 'traefik'
        static_configs:
          - targets: ['traefik:8080']
          
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['10.19.253.199:9100']