apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service
spec:
  selector:
    matchLabels:
      app: simple-web-service
  replicas: 7
  template:
    metadata:
      labels:
        app: simple-web-service
    spec:
      containers:
        - name: simple-web-service
          image: roykachouh/simple-web-service
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  selector:
    app: simple-web-service
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer